name: Create DSA Reminder

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run reminder script
        run: python .github/scripts/create_reminder.py

      - name: Move reminders.md to /reminder/
        run: |
          mkdir -p reminder
          mv reminders.md reminder/reminders.md

      - name: Commit and push reminders.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update DSA reminders"
          branch: main
          file_pattern: 'reminder/reminders.md'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
