name: DSA Questions Reminder

on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 09:00 UTC
  workflow_dispatch:

jobs:
  generate-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate reminder.md
        run: python .github/scripts/generate_reminder.py

      - name: Check if reminder.md changed
        id: check_diff
        run: |
          git fetch
          if git diff --exit-code reminder.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push reminder.md
        if: steps.check_diff.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update reminder.md with DSA questions to review"
          file_pattern: reminder.md
          github_token: ${{ secrets.GITHUB_TOKEN }}

# Note: If you have branch protection rules or are using a private repository,
# you may need to adjust permissions for the GitHub Actions workflow.